name: jupyter-mcp-sage
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - jupyterlab=4.4.1
  - notebook
  - nbformat
  - nbconvert
  - tornado
  - pyzmq
  - traitlets
  - python-dateutil
  - sagemath>=10.2
  - ipywidgets
  - matplotlib
  - numpy
  - scipy
  - sympy
  - networkx
  - pandas
  - requests
  - websockets
  - nest-asyncio
  - pip:
    - mcp>=0.1.0
    - jupyter-client>=7.0.0
    - jupyter-core>=4.7.0
    - jupyter-collaboration>=4.0.2
    - datalayer_pycrdt>=0.12.17
