name: jupyter-mcp-sage
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - jupyterlab>=4.0.0,<5.0.0
  - notebook
  - ipywidgets
  - matplotlib
  - numpy
  - scipy
  - sympy
  - pandas
  - requests
  - websockets
  - nest-asyncio
  - ipykernel
  # SageMath - core package
  - sage
  # Essential math tools
  - maxima
  # Additional scientific packages
  - cython
  - pip:
    - mcp>=0.1.0
